=== AniketosEU/Security-Service-Validation-and-Verification/ConSpec_Parser/rsc/xsd_aniketosShort.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="typeType">
		<xs:restriction base="xs:string">
			<xs:enumeration value="int" />
			<xs:enumeration value="bool" />
			<xs:enumeration value="string" />
			<xs:enumeration value="void"></xs:enumeration>
		</xs:restriction>
	</xs:simpleType>


<xs:complexType name="parameterType">
	<xs:sequence>
		<xs:element name="type" type="typeType"/>
		<xs:element name="identifier" type="xs:string"/>
	</xs:sequence>
</xs:complexType>

<xs:element name="specificationShort">
  <xs:complexType>
    <xs:sequence>
		<xs:element name="identifier" type="xs:string"/>
		<xs:element name="parameter" type="parameterType" minOccurs="0" maxOccurs="unbounded"/>              </xs:sequence>
    <xs:attribute name="id" type="xs:string"/> 
  </xs:complexType>
</xs:element>

</xs:schema>

=== AniketosEU/Security-Service-Validation-and-Verification/ConSpec_Parser/rsc/BoD_Goal_short.xml
<specificationShort id="BoD_Goal_short" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aniketosShort.xsd">
  <identifier>BoD_Goal</identifier> 
<parameter>
  <type>string</type> 
  <identifier>Book_rooms</identifier> 
  </parameter>
<parameter>
  <type>string</type> 
  <identifier>Teach_lessons</identifier> 
  </parameter>
</specificationShort>

=== AniketosEU/Security-Service-Validation-and-Verification/ConSpec_Parser/rsc/Confidentiality_short.xml
<specificationShort id="Confidentiality_short" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aniketosShort.xsd">
  <identifier>Confidentiality</identifier> 
<parameter>
  <type>string</type> 
  <identifier>Send_Document</identifier> 
  </parameter>
<parameter>
  <type>string</type> 
  <identifier>Receive_Document</identifier> 
  </parameter>
</specificationShort>

=== AniketosEU/Security-Service-Validation-and-Verification/ConSpec_Parser/rsc/SoD_Goal_short.xml
<specificationShort id="SoD_Goal_short" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="xsd_aniketosShort.xsd">
  <identifier>SoD_Goal</identifier> 
<parameter>
  <type>string</type> 
  <identifier>Get_Loan</identifier> 
  </parameter>
<parameter>
  <type>string</type> 
  <identifier>Approve_Loan</identifier> 
  </parameter>
</specificationShort>
